name: Content Issues
description: Report missing, out of date, or incorrect content
labels: ["content", "triage"]
assignees:
  - sneat
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this report!
  - type: textarea
    id: what-happened
    attributes:
      label: "What's wrong?"
      description: Please explain the content error in clear detail, providing the location of the error and the location of the content in the PDF if available. You can paste screenshots if that helps.
      placeholder: |
        In the Adventure Tables Journal Entry, the first table says that Owl Bears have six hit dice, but according to the PDF on page 213 they have HD 5.
    validations:
      required: true
  - type: dropdown
    id: package-id
    attributes:
      label: Which package?
      description: Select the Necrotic Gnome product with this issue.
      options:
        - Advanced Fantasy
        - Halls of the Blood King
        - Holy Mountain Shaker
        - The Hole in the Oak
        - The Incandescent Grottoes
        - The Isle of the Plangent Mage
        - Winter's Daughter
        - Carcass Crawler Issue One
        - Carcass Crawler Issue Two
        - Carcass Crawler Issue Three
  - type: input
    id: package-version
    attributes:
      label: Package Version
      description: Which version of this package are you using?
  - type: input
    id: pdf-version
    attributes:
      label: PDF Version
      description: If you are verifying your information against the official PDF, what version of the PDF are you using?
